### ISSUE TITLE
Namespace prefix xsi for type on argument is not defined

### ISSUE THREAD

**Issue by dwdonline** [samsteele/spam-registration-blocker#1]
With the changes on April 2, the plugin now throws an exception:

[Exception]                                                                                                                              
  Warning: DOMDocument::load(): Namespace prefix xsi for type on argument is not defined in /.../public_html/vendor/samsteele/spam-registration-blocker/etc/di.xml, line: 17 in /.../public_html/setup/src/Magento/Setup/Module/Di/Code/Scanner/XmlScanner.php on line 36

**Comment by samsteele** [comment]
👋 Now working!
